#PBS -N MPIHW2_revised
#PBS -l nodes=1:core12
#PBS -l walltime=00:30:00
#PBS -q coc-ice

cd /nv/ice/kzheng46/prog2

module load gcc
module load mvapich2/2.2

make clean
make all > make.log 2>&1

echo "********************"
for n in {100..2000..100}; do
    for d in 0.0 0.2 0.4 0.6 0.8 1.0 ; do
        for nprocs in 1 4 9 ; do
            echo "n = " $n ", d = " $d ", nprocs = " $nprocs 1>&2
            mpirun -np $nprocs ./jacobi -n $n -d $d
        done
        echo "********************"
    done
done
